version: "3.2"

services:
  api: 
    build: ./images/api
    ports:
      - 3000:3000
    volumes:
      - ./images/api/src:/usr/app/src
    environment:
      POSTGRES_DB:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
      POSTGRES_HOST: db

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: 
      POSTGRES_USER: 
      POSTGRES_DB: 
      POSTGRES_HOST_AUTH_METHOD: 
    ports:
      - 5432:5432
    volumes:
      - ./_volumes/db:/var/lib/postgresql/data
